const http = require("http");
const os = require("os");

const PORT = process.env.PORT || 3000;

const server = http.createServer((req, res) => {
	  res.writeHead(200, { "Content-Type": "text/html" });

	  res.end(`<!DOCTYPE html>
	  <html lang="en">
	  <head>
	    <meta charset="UTF-8" />
	      <title>Live on AWS App Runner</title>
	        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

		  <style>
		      :root {
		            --bg1: #0f2027;
			          --bg2: #203a43;
				        --bg3: #2c5364;
					      --accent: #00e5ff;
					            --card-bg: rgba(255,255,255,0.1);
						        }

							    * {
							    *       box-sizing: border-box;
							    *             margin: 0;
							    *                   padding: 0;
							    *                         font-family: "Segoe UI", system-ui, -apple-system, BlinkMacSystemFont;
							    *                             }
							    *
							    *                                 body {
							    *                                       min-height: 100vh;
							    *                                             background: linear-gradient(-45deg, var(--bg1), var(--bg2), var(--bg3));
							    *                                                   background-size: 400% 400%;
							    *                                                         animation: gradient 15s ease infinite;
							    *                                                               color: #fff;
							    *                                                                     display: flex;
							    *                                                                           justify-content: center;
							    *                                                                                 align-items: center;
							    *                                                                                       padding: 20px;
							    *                                                                                           }
							    *
							    *                                                                                               @keyframes gradient {
							    *                                                                                                     0% { background-position: 0% 50%; }
							    *                                                                                                           50% { background-position: 100% 50%; }
							    *                                                                                                                 100% { background-position: 0% 50%; }
							    *                                                                                                                     }
							    *
							    *                                                                                                                         .container {
							    *                                                                                                                               max-width: 1100px;
							    *                                                                                                                                     width: 100%;
							    *                                                                                                                                         }
							    *
							    *                                                                                                                                             .hero {
							    *                                                                                                                                                   text-align: center;
							    *                                                                                                                                                         margin-bottom: 40px;
							    *                                                                                                                                                             }
							    *
							    *                                                                                                                                                                 .badge {
							    *                                                                                                                                                                       display: inline-block;
							    *                                                                                                                                                                             padding: 6px 14px;
							    *                                                                                                                                                                                   border-radius: 20px;
							    *                                                                                                                                                                                         background: rgba(0, 229, 255, 0.2);
							    *                                                                                                                                                                                               color: var(--accent);
							    *                                                                                                                                                                                                     font-weight: 600;
							    *                                                                                                                                                                                                           margin-bottom: 15px;
							    *                                                                                                                                                                                                               }
							    *
							    *                                                                                                                                                                                                                   h1 {
							    *                                                                                                                                                                                                                         font-size: 3rem;
							    *                                                                                                                                                                                                                               margin-bottom: 10px;
							    *                                                                                                                                                                                                                                   }
							    *
							    *                                                                                                                                                                                                                                       h1 span {
							    *                                                                                                                                                                                                                                             color: var(--accent);
							    *                                                                                                                                                                                                                                                 }
							    *
							    *                                                                                                                                                                                                                                                     p.subtitle {
							    *                                                                                                                                                                                                                                                           font-size: 1.2rem;
							    *                                                                                                                                                                                                                                                                 opacity: 0.9;
							    *                                                                                                                                                                                                                                                                     }
							    *
							    *                                                                                                                                                                                                                                                                         .grid {
							    *                                                                                                                                                                                                                                                                               display: grid;
							    *                                                                                                                                                                                                                                                                                     grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
							    *                                                                                                                                                                                                                                                                                           gap: 25px;
							    *                                                                                                                                                                                                                                                                                                 margin-top: 40px;
							    *                                                                                                                                                                                                                                                                                                     }
							    *
							    *                                                                                                                                                                                                                                                                                                         .card {
							    *                                                                                                                                                                                                                                                                                                               background: var(--card-bg);
							    *                                                                                                                                                                                                                                                                                                                     backdrop-filter: blur(12px);
							    *                                                                                                                                                                                                                                                                                                                           border-radius: 16px;
							    *                                                                                                                                                                                                                                                                                                                                 padding: 25px;
							    *                                                                                                                                                                                                                                                                                                                                       box-shadow: 0 10px 30px rgba(0,0,0,0.25);
							    *                                                                                                                                                                                                                                                                                                                                             transition: transform 0.3s ease, box-shadow 0.3s ease;
							    *                                                                                                                                                                                                                                                                                                                                                 }
							    *
							    *                                                                                                                                                                                                                                                                                                                                                     .card:hover {
							    *                                                                                                                                                                                                                                                                                                                                                           transform: translateY(-8px);
							    *                                                                                                                                                                                                                                                                                                                                                                 box-shadow: 0 20px 40px rgba(0,0,0,0.4);
							    *                                                                                                                                                                                                                                                                                                                                                                     }
							    *
							    *                                                                                                                                                                                                                                                                                                                                                                         .card h3 {
							    *                                                                                                                                                                                                                                                                                                                                                                               margin-bottom: 10px;
							    *                                                                                                                                                                                                                                                                                                                                                                                     color: var(--accent);
							    *                                                                                                                                                                                                                                                                                                                                                                                         }
							    *
							    *                                                                                                                                                                                                                                                                                                                                                                                             .card p {
							    *                                                                                                                                                                                                                                                                                                                                                                                                   line-height: 1.6;
							    *                                                                                                                                                                                                                                                                                                                                                                                                         opacity: 0.95;
							    *                                                                                                                                                                                                                                                                                                                                                                                                               font-size: 0.95rem;
							    *                                                                                                                                                                                                                                                                                                                                                                                                                   }
							    *
							    *                                                                                                                                                                                                                                                                                                                                                                                                                       footer {
							    *                                                                                                                                                                                                                                                                                                                                                                                                                             text-align: center;
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                   margin-top: 50px;
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                         font-size: 0.85rem;
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                               opacity: 0.7;
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                     </style>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                     </head>
							    *
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                     <body>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                       <div class="container">
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                           <div class="hero">
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <div class="badge">● LIVE</div>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <h1>Hello from <span>AWS App Runner</span></h1>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <p class="subtitle">
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Production-grade Node.js container deployed via GitHub Actions & Amazon ECR
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </p>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </div>
							    *
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <div class="grid">
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <div class="card">
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <h3>🚀 Deployment</h3>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <p>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Fully automated CI/CD pipeline using GitHub Actions.  
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Docker image built, pushed to Amazon ECR, and deployed on App Runner.
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </p>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>
							    *
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <div class="card">
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <h3>☁️ Platform</h3>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <p>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Managed container service with automatic scaling, HTTPS, and zero server management.
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Powered by AWS App Runner.
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </p>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </div>
							    *
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <div class="card">
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 <h3>📊 Runtime Info</h3>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         <p>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Hostname: <b>${os.hostname()}</b><br/>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Server Time: <b>${new Date().toLocaleString()}</b><br/>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Platform: <b>${os.platform()}</b>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </p>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
							    *
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <div class="card">
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <h3>🔐 Security</h3>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <p>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Images stored in private Amazon ECR.  
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               CI/CD authenticated securely via GitHub Secrets (Org-restricted account).
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </p>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
							    *
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <footer>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           © ${new Date().getFullYear()} • Built by Shubham Mishra • AWS App Runner Demo
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               </footer>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </body>
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </html>`);
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 });
							    *
							    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 server.listen(PORT, () => {
									    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   console.log(`Server running on port ${PORT}`);
									    *                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   });
							    *
